CREATE VIEW VIEW1 AS SELECT *FROM KRATHSH WHERE BILL>20;
CREATE VIEW VIEW2 AS SELECT 
TRAPEZI.FLOOR,PELATIS.LNAME,PELATIS.FNAME,KRATHSH.BILL,reservationno
FROM TRAPEZI,KRATHSH,PELATIS;
CREATE VIEW VIEW3 AS SELECT PROVIDES.AMENTYPE,AMENITIES.AMENCOST,
PROVIDES.TID,KRATHSH.KID,KRATHSH.PID,PELATIS.LNAME,PELATIS.FNAME 
FROM AMENITIES,PROVIDES,KRATHSH,PELATIS;
