/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WiZ14
 */
public class ConnectJDialog extends javax.swing.JDialog {
private boolean userchoosedokflag;
    /**
     * Creates new form ConnectJDialog
     */
    public ConnectJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        userchoosedokflag=false;
        initComponents();
    }
    public String getusername(){
        return this.JusernameText.getText();
    }
    public String getpassword(){
        return this.JpasswordText.getText();
    }
    public String getconnectstring(){
        return this.JconnectstringText.getText();
    }
    public boolean getuserchoosedokflag(){
        return userchoosedokflag;
    }
    public void okaction(){
        userchoosedokflag=true;dispose();
    }
    public void cancelaction(){
        userchoosedokflag=false;dispose();
    }
    public void okenablecheck(){
       if ((JusernameText.getText().length() > 0)&&
          (JpasswordText.getText().length() > 0)&&
          (JconnectstringText.getText().length() > 0)) 
        {JokButton.setEnabled(true);} 
        else{JcancelButton.setEnabled(false);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JokButton = new javax.swing.JButton();
        JcancelButton = new javax.swing.JButton();
        JusernameText = new javax.swing.JTextField();
        JpasswordText = new javax.swing.JTextField();
        JconnectstringText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("username");

        jLabel2.setText("password");

        jLabel3.setText("connectstring");

        JokButton.setText("ok");
        JokButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JokButtonActionPerformed(evt);
            }
        });

        JcancelButton.setText("cancel");
        JcancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcancelButtonActionPerformed(evt);
            }
        });

        JusernameText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JusernameTextCaretUpdate(evt);
            }
        });
        JusernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JusernameTextActionPerformed(evt);
            }
        });

        JpasswordText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JpasswordTextCaretUpdate(evt);
            }
        });
        JpasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpasswordTextActionPerformed(evt);
            }
        });

        JconnectstringText.setEditable(false);
        JconnectstringText.setText("jdbc:oracle:thin:@127.0.0.1:1521:xe");
        JconnectstringText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JconnectstringTextCaretUpdate(evt);
            }
        });
        JconnectstringText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JconnectstringTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JcancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JokButton)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JusernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(JpasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JconnectstringText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JusernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JpasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JokButton)
                        .addGap(26, 26, 26)
                        .addComponent(JcancelButton)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(JconnectstringText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JconnectstringTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JconnectstringTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JconnectstringTextActionPerformed

    private void JokButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JokButtonActionPerformed
        // TODO add your handling code here:
        okaction();
    }//GEN-LAST:event_JokButtonActionPerformed

    private void JcancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcancelButtonActionPerformed
        // TODO add your handling code here:
      cancelaction();
    }//GEN-LAST:event_JcancelButtonActionPerformed

    private void JusernameTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JusernameTextCaretUpdate
        // TODO add your handling code here:
        okenablecheck();
    }//GEN-LAST:event_JusernameTextCaretUpdate

    private void JpasswordTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JpasswordTextCaretUpdate
        // TODO add your handling code here:
                okenablecheck();
    }//GEN-LAST:event_JpasswordTextCaretUpdate

    private void JconnectstringTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JconnectstringTextCaretUpdate
        // TODO add your handling code here:
                okenablecheck();
    }//GEN-LAST:event_JconnectstringTextCaretUpdate

    private void JusernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JusernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JusernameTextActionPerformed

    private void JpasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpasswordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConnectJDialog dialog = new ConnectJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JcancelButton;
    private javax.swing.JTextField JconnectstringText;
    private javax.swing.JButton JokButton;
    private javax.swing.JTextField JpasswordText;
    private javax.swing.JTextField JusernameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
