/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author WiZ14
 */
public class DeliciousJframe extends javax.swing.JFrame {
    public static Connection con;
    /**
     * Creates new form DeliciousJframe
     */
    public void exitAction(){
        this.dispose();
    }
    public DeliciousJframe() {
        initComponents();
    }
    public void connectaction(){
        ConnectJDialog connectdialog1=new ConnectJDialog(this,true);
        connectdialog1.setVisible(true);
        if(connectdialog1.getuserchoosedokflag()==false){return;}
    try{Class.forName("oracle.jdbc.driver.OracleDriver");
    con = DriverManager.getConnection(connectdialog1.getconnectstring(), connectdialog1.getusername(), connectdialog1.getpassword());
    JconnectMenuItem.setEnabled(false);}
    catch(java.sql.SQLException e1){JOptionPane.showMessageDialog(this,e1.getMessage() );}
    catch(Exception e2){JOptionPane.showMessageDialog(this,e2.getMessage() );}
    setactionstatus();
    }
    public void disconnectaction(){
        try{con.close();JconnectMenuItem.setEnabled(true);}
        catch(java.sql.SQLException e3){JOptionPane.showMessageDialog(this,e3.getMessage() );
}setactionstatus();
    }
    public void setactionstatus(){
        if (JconnectMenuItem.isEnabled()==false){
JdisconnectMenuItem.setEnabled(true);JEditMenu.setEnabled(true);}
else{JdisconnectMenuItem.setEnabled(false);JEditMenu.setEnabled(false);}        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        JFileMenu = new javax.swing.JMenu();
        JconnectMenuItem = new javax.swing.JMenuItem();
        JdisconnectMenuItem = new javax.swing.JMenuItem();
        JexitMenuItem = new javax.swing.JMenuItem();
        JEditMenu = new javax.swing.JMenu();
        JPelatisMenuItem = new javax.swing.JMenuItem();
        JKrathshMenuItem = new javax.swing.JMenuItem();
        JTrapeziMenuItem = new javax.swing.JMenuItem();
        JKathgoriesMenuItem = new javax.swing.JMenuItem();
        JPhoneMenuItem = new javax.swing.JMenuItem();
        JAmenitiesMenuItem = new javax.swing.JMenuItem();
        JProvidesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JFileMenu.setText("File");

        JconnectMenuItem.setText("Connect");
        JconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JconnectMenuItemActionPerformed(evt);
            }
        });
        JFileMenu.add(JconnectMenuItem);

        JdisconnectMenuItem.setText("Disconnect");
        JdisconnectMenuItem.setEnabled(false);
        JdisconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JdisconnectMenuItemActionPerformed(evt);
            }
        });
        JFileMenu.add(JdisconnectMenuItem);

        JexitMenuItem.setText("Exit");
        JexitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JExitItemActionPerformed(evt);
            }
        });
        JFileMenu.add(JexitMenuItem);

        jMenuBar1.add(JFileMenu);

        JEditMenu.setText("Edit");
        JEditMenu.setEnabled(false);

        JPelatisMenuItem.setText("Customers");
        JPelatisMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPelatisMenuItemActionPerformed(evt);
            }
        });
        JEditMenu.add(JPelatisMenuItem);

        JKrathshMenuItem.setText("Reservations");
        JKrathshMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKrathshMenuItemActionPerformed(evt);
            }
        });
        JEditMenu.add(JKrathshMenuItem);

        JTrapeziMenuItem.setText("Tables");
        JTrapeziMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTrapeziMenuItemActionPerformed(evt);
            }
        });
        JEditMenu.add(JTrapeziMenuItem);

        JKathgoriesMenuItem.setText("TableCategories");
        JKathgoriesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKathgoriesMenuItemActionPerformed(evt);
            }
        });
        JEditMenu.add(JKathgoriesMenuItem);

        JPhoneMenuItem.setText("Phones");
        JPhoneMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPhoneMenuItemActionPerformed(evt);
            }
        });
        JEditMenu.add(JPhoneMenuItem);

        JAmenitiesMenuItem.setText("Amenities");
        JAmenitiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAmenitiesMenuItemActionPerformed(evt);
            }
        });
        JEditMenu.add(JAmenitiesMenuItem);

        JProvidesMenuItem.setText("TableAmenities");
        JProvidesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JProvidesMenuItemActionPerformed(evt);
            }
        });
        JEditMenu.add(JProvidesMenuItem);

        jMenuBar1.add(JEditMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JExitItemActionPerformed
        // TODO add your handling code here:
        exitAction();
    }//GEN-LAST:event_JExitItemActionPerformed

    private void JconnectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JconnectMenuItemActionPerformed
        // TODO add your handling code here:
        connectaction();
    }//GEN-LAST:event_JconnectMenuItemActionPerformed

    private void JdisconnectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JdisconnectMenuItemActionPerformed
        // TODO add your handling code here:
        disconnectaction();
    }//GEN-LAST:event_JdisconnectMenuItemActionPerformed

    private void JPelatisMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPelatisMenuItemActionPerformed
        // TODO add your handling code here:
        new PelatisJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_JPelatisMenuItemActionPerformed

    private void JKrathshMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKrathshMenuItemActionPerformed
        // TODO add your handling code here:
        new KrathshJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_JKrathshMenuItemActionPerformed

    private void JTrapeziMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTrapeziMenuItemActionPerformed
        // TODO add your handling code here:
         new TrapeziJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_JTrapeziMenuItemActionPerformed

    private void JKathgoriesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKathgoriesMenuItemActionPerformed
        // TODO add your handling code here:
        new KathgoriesJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_JKathgoriesMenuItemActionPerformed

    private void JPhoneMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPhoneMenuItemActionPerformed
        // TODO add your handling code here:
         new PhoneJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_JPhoneMenuItemActionPerformed

    private void JAmenitiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAmenitiesMenuItemActionPerformed
        // TODO add your handling code here:
        new AmenitiesJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_JAmenitiesMenuItemActionPerformed

    private void JProvidesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JProvidesMenuItemActionPerformed
        // TODO add your handling code here:
        new ProvidesJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_JProvidesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliciousJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliciousJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliciousJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliciousJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliciousJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JAmenitiesMenuItem;
    private javax.swing.JMenu JEditMenu;
    private javax.swing.JMenu JFileMenu;
    private javax.swing.JMenuItem JKathgoriesMenuItem;
    private javax.swing.JMenuItem JKrathshMenuItem;
    private javax.swing.JMenuItem JPelatisMenuItem;
    private javax.swing.JMenuItem JPhoneMenuItem;
    private javax.swing.JMenuItem JProvidesMenuItem;
    private javax.swing.JMenuItem JTrapeziMenuItem;
    private javax.swing.JMenuItem JconnectMenuItem;
    private javax.swing.JMenuItem JdisconnectMenuItem;
    private javax.swing.JMenuItem JexitMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
