ALTER TABLE KRATHSH ADD reservationNo number;
CREATE SEQUENCE CustSeq INCREMENT BY 1 START WITH 1;
update KRATHSH SET reservationNO=CustSeq.NEXTVAL;
CREATE SEQUENCE CustSeq2 INCREMENT BY 1 START WITH 15;
drop sequence CustSeq2; 
ALTER TABLE PELATIS MODIFY PID varchar2(20);
insert into PELATIS VALUES (CustSeq2.NEXTVAL,'NIKOU','NIKOS',TO_DATE('19/02/19','DD-MM-YY'),'233AT')